
name: Go Build Test

on:
  push:
    branches: [ main ]
    paths:
      - 'config/atlas_go/**'
  pull_request:
    paths:
      - 'config/atlas_go/**'

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Go App
      run: |
        cd config/atlas_go
        go build -v ./...
